### ISSUE TITLE
Multiple drummaps

### ISSUE THREAD

**Issue by NikolaiVChr** [digero/maestro#17]
I have 4 drummaps that I switch between.
Having them loaded into Maestro, and selectable via a dropdown menu could be cool.

**Comment by digero** [comment]
With unlimited time, this isn't a bad idea. But given that it currently takes 3 clicks to switch drum maps via the Import dialog, and this would reduce it to 2 clicks, it's a pretty low priority change. Since I don't have much spare time to work on Maestro, any time would be spent doing higher priority stuff. So I'm just going to mark this as wontfix, sorry!
