### ISSUE TITLE
I already have Java 8 but it wants 7?

### ISSUE THREAD

**Issue by minyassa** [digero/maestro#22]
I'd thought that 64-bit apps kind of covered all 32-bit apps as well, but it's acting like I don't have Java at all. It says: "Maestro requires Java 7 (32-bit) or later. Visit http://java.com to download it."

**Comment by digero** [comment]
Hi @minyassa, Maestro works with Java 8, but it does require* 32-bit Java. You can have both 32-bit and 64-bit Java installed at the same time.

[* It is possible to use 64-bit Java if you want, but you need to start the app via Maestro.jar in the installation folder instead of Maestro.exe. (If you're not sure what that means, I'd really recommend just installing 32-bit Java.) If you choose to use Maestro.jar instead, you won't be able to double-click on Maestro or ABC files to open them, but you can start Maestro and then open the file from within the app.]
